/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-class`; params?: Router.UnknownInputParams; } | { pathname: `/adduserbyadmin`; params?: Router.UnknownInputParams; } | { pathname: `/adminHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/classmanagement`; params?: Router.UnknownInputParams; } | { pathname: `/forgetPassowrd`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/manageUser`; params?: Router.UnknownInputParams; } | { pathname: `/sectionmanagement`; params?: Router.UnknownInputParams; } | { pathname: `/setting`; params?: Router.UnknownInputParams; } | { pathname: `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/studentHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/studentManage`; params?: Router.UnknownInputParams; } | { pathname: `/teacherHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../thunk/section/getsectionDetails`; params?: Router.UnknownInputParams; } | { pathname: `/../redux/slice/sectionSlice/getSectionSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tab/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tab`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-class`; params?: Router.UnknownOutputParams; } | { pathname: `/adduserbyadmin`; params?: Router.UnknownOutputParams; } | { pathname: `/adminHomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/classmanagement`; params?: Router.UnknownOutputParams; } | { pathname: `/forgetPassowrd`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/manageUser`; params?: Router.UnknownOutputParams; } | { pathname: `/sectionmanagement`; params?: Router.UnknownOutputParams; } | { pathname: `/setting`; params?: Router.UnknownOutputParams; } | { pathname: `/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/studentHomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/studentManage`; params?: Router.UnknownOutputParams; } | { pathname: `/teacherHomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../thunk/section/getsectionDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/../redux/slice/sectionSlice/getSectionSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tab/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/tab`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-class${`?${string}` | `#${string}` | ''}` | `/adduserbyadmin${`?${string}` | `#${string}` | ''}` | `/adminHomeScreen${`?${string}` | `#${string}` | ''}` | `/classmanagement${`?${string}` | `#${string}` | ''}` | `/forgetPassowrd${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/manageUser${`?${string}` | `#${string}` | ''}` | `/sectionmanagement${`?${string}` | `#${string}` | ''}` | `/setting${`?${string}` | `#${string}` | ''}` | `/Signup${`?${string}` | `#${string}` | ''}` | `/studentHomeScreen${`?${string}` | `#${string}` | ''}` | `/studentManage${`?${string}` | `#${string}` | ''}` | `/teacherHomeScreen${`?${string}` | `#${string}` | ''}` | `/../thunk/section/getsectionDetails${`?${string}` | `#${string}` | ''}` | `/../redux/slice/sectionSlice/getSectionSlice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tab/explore${`?${string}` | `#${string}` | ''}` | `/tab${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-class`; params?: Router.UnknownInputParams; } | { pathname: `/adduserbyadmin`; params?: Router.UnknownInputParams; } | { pathname: `/adminHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/classmanagement`; params?: Router.UnknownInputParams; } | { pathname: `/forgetPassowrd`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/manageUser`; params?: Router.UnknownInputParams; } | { pathname: `/sectionmanagement`; params?: Router.UnknownInputParams; } | { pathname: `/setting`; params?: Router.UnknownInputParams; } | { pathname: `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/studentHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/studentManage`; params?: Router.UnknownInputParams; } | { pathname: `/teacherHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../thunk/section/getsectionDetails`; params?: Router.UnknownInputParams; } | { pathname: `/../redux/slice/sectionSlice/getSectionSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tab/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tab`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
